// 65-07: Rule-type audit.
// Walks the three allow-listed PF2e effect packs in D:/parse_data/…,
// collects the distribution of rule `key` values across every effect's
// `system.rules[]`, and cross-references against the engine's supported
// rule-type list. Asserts engine parses are present for the core set
// (FlatModifier, Resistance, RollOption, RollTwice, AdjustStrike,
// DamageDice, CreatureSize, BattleForm, Note, GrantItem). ChoiceSet and
// DexterityModifierCap are documented as intentionally ignored.
//
// Writes `.planning/reports/rule-type-audit-v1.4.md`. If the PAKS path is
// absent (developer without parse_data), the test is skipped gracefully —
// no hard dependency on the external data source.

import { describe, it, expect } from 'vitest'
import { readdirSync, readFileSync, existsSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'

const PAKS_ROOT = 'D:/parse_data/PAKS/pf2e/packs/pf2e'
const PACKS = ['spell-effects', 'equipment-effects', 'boons-and-curses'] as const

const SUPPORTED_RULE_KEYS = new Set([
  'FlatModifier',
  'Resistance',
  'RollOption',
  'RollTwice',
  'AdjustStrike',
  'DamageDice',
  'CreatureSize',
  'BattleForm',
  'Note',
  'GrantItem',
])

const INTENTIONALLY_IGNORED = new Set([
  'ChoiceSet',          // user-interactive selection — requires UI prompt
  'DexterityModifierCap', // armor DEX cap — not modeled in Phase 65
])

function collectPackRules(packPath: string): {
  ruleKeyCounts: Record<string, number>
  fileCount: number
} {
  if (!existsSync(packPath)) return { ruleKeyCounts: {}, fileCount: 0 }
  const counts: Record<string, number> = {}
  let fileCount = 0
  for (const entry of readdirSync(packPath)) {
    if (!entry.endsWith('.json')) continue
    fileCount += 1
    let doc: Record<string, unknown>
    try {
      doc = JSON.parse(readFileSync(join(packPath, entry), 'utf-8'))
    } catch {
      continue
    }
    const system = doc.system as Record<string, unknown> | undefined
    if (!system) continue
    const rules = system.rules
    if (!Array.isArray(rules)) continue
    for (const rule of rules) {
      const key =
        rule && typeof rule === 'object' && 'key' in rule
          ? String((rule as { key: unknown }).key ?? '')
          : ''
      if (!key) continue
      counts[key] = (counts[key] ?? 0) + 1
    }
  }
  return { ruleKeyCounts: counts, fileCount }
}

function supportLabel(key: string): 'yes' | 'no' | 'ignored' {
  if (SUPPORTED_RULE_KEYS.has(key)) return 'yes'
  if (INTENTIONALLY_IGNORED.has(key)) return 'ignored'
  return 'no'
}

function renderReport(
  results: Array<{ pack: string; fileCount: number; counts: Record<string, number> }>,
): string {
  const lines: string[] = []
  lines.push('# Rule-Type Audit — v1.4 Phase 65')
  lines.push('')
  lines.push(
    'Auto-generated by `engine/effects/__tests__/rule-type-audit.test.ts`. ' +
      'Walks every JSON file under the three allow-listed PF2e effect packs ' +
      '(`D:/parse_data/PAKS/pf2e/packs/pf2e/{spell-effects,equipment-effects,boons-and-curses}`) ' +
      'and tallies each `system.rules[].key` value.',
  )
  lines.push('')
  lines.push('**Support column:**')
  lines.push('- `yes` — engine has a parser + apply-path landing in Phase 65')
  lines.push('- `ignored` — explicitly out of scope (documented below)')
  lines.push('- `no` — gap; future phase candidate')
  lines.push('')

  // Aggregate across all packs for the top summary.
  const overall: Record<string, number> = {}
  let totalFiles = 0
  for (const r of results) {
    totalFiles += r.fileCount
    for (const [k, v] of Object.entries(r.counts)) {
      overall[k] = (overall[k] ?? 0) + v
    }
  }

  lines.push(`## Summary (${totalFiles} effect files across ${results.length} packs)`)
  lines.push('')
  lines.push('| Rule Key | Occurrences | Support |')
  lines.push('|---|---:|:---:|')
  const sortedOverall = Object.entries(overall).sort((a, b) => b[1] - a[1])
  for (const [k, n] of sortedOverall) {
    lines.push(`| \`${k}\` | ${n} | ${supportLabel(k)} |`)
  }
  lines.push('')

  for (const r of results) {
    lines.push(`## Pack: \`${r.pack}\` (${r.fileCount} files)`)
    lines.push('')
    const rows = Object.entries(r.counts).sort((a, b) => b[1] - a[1])
    if (rows.length === 0) {
      lines.push('_No rules found._')
      lines.push('')
      continue
    }
    lines.push('| Rule Key | Occurrences | Support |')
    lines.push('|---|---:|:---:|')
    for (const [k, n] of rows) {
      lines.push(`| \`${k}\` | ${n} | ${supportLabel(k)} |`)
    }
    lines.push('')
  }

  lines.push('## Explicitly ignored')
  lines.push('')
  lines.push(
    '- `ChoiceSet` — requires a user-interactive prompt at effect-apply time. ' +
      'Phase 65 resolves effects whose ChoiceSet produces a literal (Enlarge → ' +
      '`{ size: "large" }`) by parsing the sibling CreatureSize / BattleForm rule; ' +
      'effects that strictly depend on user selection (Dragon Form, Draconic Barrage) ' +
      'apply the static default and do not expose the picker yet.',
  )
  lines.push(
    '- `DexterityModifierCap` — Foundry enforces the cap at AC computation time ' +
      'using a dedicated pipeline stage we do not yet model. Mutagen bonuses ' +
      'to AC land via their sibling `FlatModifier` rule; the cap is simply not ' +
      'enforced for Phase 65 — tracked as a future phase.',
  )
  lines.push('')
  lines.push('_Report generated deterministically from PAKS; re-run the audit test to refresh._')
  lines.push('')

  return lines.join('\n')
}

describe('rule-type audit across allow-listed PF2e effect packs', () => {
  it('covers the core rule-types and writes the audit report', () => {
    if (!existsSync(PAKS_ROOT)) {
      console.warn(`[rule-type-audit] PAKS_ROOT missing (${PAKS_ROOT}); skipping.`)
      return
    }

    const results = PACKS.map((pack) => {
      const { ruleKeyCounts, fileCount } = collectPackRules(join(PAKS_ROOT, pack))
      return { pack, counts: ruleKeyCounts, fileCount }
    })

    // Assert at least one file was parsed from each pack — otherwise the
    // PAKS layout drifted and the audit is meaningless.
    for (const r of results) {
      expect(r.fileCount, `pack ${r.pack} returned no files`).toBeGreaterThan(0)
    }

    // Core rule-types MUST be claimed as supported in the engine.
    for (const required of [
      'FlatModifier',
      'Resistance',
      'RollOption',
      'AdjustStrike',
      'BattleForm',
      'Note',
      'GrantItem',
    ]) {
      expect(SUPPORTED_RULE_KEYS.has(required)).toBe(true)
    }

    // Ignored list is explicit — regression guard.
    expect(INTENTIONALLY_IGNORED.has('ChoiceSet')).toBe(true)
    expect(INTENTIONALLY_IGNORED.has('DexterityModifierCap')).toBe(true)

    const report = renderReport(results)
    const out = '.planning/reports/rule-type-audit-v1.4.md'
    mkdirSync(dirname(out), { recursive: true })
    writeFileSync(out, report, 'utf-8')
    expect(existsSync(out)).toBe(true)
  })
})
