export { useCombatantStore } from './model/store'
export { createCombatantFromCharacter, createCharacterGroupCombatants, toEncounterCombatant } from './lib/character'
export { resetCombatant } from './lib/reset-combatant'
export type { CombatantState } from './model/store'
export type { Combatant, NpcCombatant, PcCombatant, HazardCombatant, CombatantPatch, StagingCombatant } from './model/types'
export { isNpc, isPc, isHazardCombatant, kindFromLegacy } from './model/types'
