export const PATHS = {
  HOME: '/',
  COMBAT: '/combat',
  BESTIARY: '/bestiary',
  ENCOUNTERS: '/encounters',
  CAMPAIGNS: '/campaigns',
  CONDITIONS: '/conditions',
  SPELLS: '/spells',
  ITEMS: '/items',
  CHARACTERS: '/characters',
  CUSTOM_CREATURES: '/custom-creatures',
  CUSTOM_CREATURE_EDIT: (id: string) => `/custom-creatures/${id}/edit`,
  CUSTOM_ITEMS: '/custom-items',
  CUSTOM_ITEM_EDIT: (id: string) => `/custom-items/${id}/edit`,
  SETTINGS: '/settings',
  HAZARDS: '/hazards',
  ACTIONS: '/actions',
} as const
